version: '3.5'

services:
#  cinemamicroserive:
#    image: cinemamicroservice
#    container_name:
#    build:
#      context:
#      dockerfile:
#    environment:
#      SERVER_PORT: 5540
#      DYNAMODB:
#      AWS_ACCESS_KEY_ID:
#      AWS_SECRET_ACCESS_KEY:
#      DYNAMODB_LOCAL: 'true'



  local-cinemamicroservice:
    image: amazon/dynamodb-local:latest
    container_name: cinemamicroservice
    entrypoint: java
    command: "-jar DynamoDB.jar -sharedDB -dbPath / data"
    restart: always
    volumes:
      - ./dynamodb:/data
    ports:
      - "8000:8000"
volumes:
  dynamodb:
    external: true