version: '3.5'

services:
  cinemamicroservice:
    image: cinemamicroservice
    container_name: cinemamicroservice
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 5540
      DYNAMODB_ENDPOINT: http://local-cinema:8000
      AWS_ACCESS_KEY_ID: LOCAL_DUMMY_KEY
      AWS_SECRET_ACCESS_KEY: LOCAL_DUMMY_KEY
      DYNAMODB_LOCAL: 'true'
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socet,address=15540,server=y,suspend=n
    ports:
      - "5540:5540"
      - "15540:15540"

  local-cinemamicroservice:
    image: amazon/dynamodb-local:latest
    container_name: cinemamicroservice
    entrypoint: java
    command: "-jar DynamoDB.jar -sharedDB -dbPath / data"
    restart: always
    volumes:
      - ./dynamodb:/data
    ports:
      - "8000:8000"
volumes:
  dynamodb:
    external: true